# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any necessary dependencies (if you have a requirements.txt file)
# RUN pip install -r requirements.txt

# Specify the command to run your application
CMD ["python", "your_script.py"]
